# fly.toml for ollama-service-pxo3vw

app = "ollama-service-pxo3vw"
primary_region = "ord"

[build]
  # No build config here—using the Docker image directly.

# Declare your runtime VM resources
[[vm]]
  memory    = "1gb"
  cpu_kind  = "shared"
  cpus      = 1
  memory_mb = 1024

# Services tells Fly how to route traffic into your app
[[services]]
  protocol = "tcp"
  internal_port = 11434

  # Expose port 80 on the public internet as HTTP,
  # forwarding requests to internal_port.
  [[services.ports]]
    port      = 80
    handlers  = ["http"]

  # (Optional) health checks
  [[services.http_checks]]
    path     = "/healthz"
    protocol = "http"
    interval = 10000
    timeout  = 2000
    method   = "GET"
