# fly.toml for ollama-service-pxo3vw

app = "ollama-service-pxo3vw"
primary_region = "ord"

[build]

[[vm]]
  memory    = "1gb"
  cpu_kind  = "shared"
  cpus      = 1
  memory_mb = 1024

[[services]]
  protocol      = "tcp"
  internal_port = 11434

  [[services.ports]]
    port     = 80
    handlers = ["http"]



